w = "word"
cw = "counter-word"

words = [{w: "Paper", cw : "Scissors"},
         {w: "Scissors", cw : "Rock"} ,
         {w : "Rock", cw : "Paper"},
         {w : "Water", cw : "Paper"},
         {w : "Twig", cw : "Scissors"},
         {w : "Sword", cw : "Shield"},
         {w : "Shield", cw : "Gun"},
         {w : "Gun", cw : "Laser"},
         {w : "Flame", cw : "Water"},
         {w : "Rope", cw : "Scissors"},
         {w : "Disease", cw : "Cure"},
         {w : "Cure", cw : "Bacteria"},
         {w : "Bacteria", cw : "Flame"},
         {w : "Shadow", cw : "Light"},
         {w : "Light", cw : "Shield"},
         {w : "Virus", cw : "Cure"},
         {w : "Sound", cw : "Shield"},
         {w : "Time", cw : "Coal"},
         {w : "Fate", cw : "Logic"},
         {w : "Earthquake", cw : "Time"},
         {w : "Storm", cw : "Time"},
         {w : "Vaccine", cw : "Logic"},
         {w : "Logic", cw : "Karma"},
         {w : "Gravity", cw : "Light"},
         {w : "Robots", cw : "Time"},
         {w : "Stone", cw : "Earthquaks"},
         {w : "Echo", cw : "Shield"},
         {w : "Thunder", cw : "Time"},
         {w : "Karma", cw : "Fate"},
         {w : "Wind", cw : "Shield"},
         {w : "Ice", cw : "Flame"},
         {w : "Sandstorm", cw : "Time"}]